services:
  - type: web
    name: gausewa_backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: gausewa
      - key: JWT_SECRET
        generateValue: true
      - key: USE_LOCAL_DB
        value: "0"
